<?php
require_once 'Zend/Date.php';

class OpeningHoursField extends TimeField {

	protected $morningOnly = false;

	protected $afternoonOnly = false;

	/**
	 * @todo This should be generated by JavaScript, but we don't have the date libraries'
	 */
	function Field($properties = array()) {
		$this->addExtraClass('timedropdownfield');
		$this->addExtraClass('openingHoursField');
		if($this->morningOnly || !$this->afternoonOnly) {
			$this->addExtraClass('morningOnly');
		}
		if($this->afternoonOnly) {
			$this->addExtraClass('afternoonOnly');
		}
		$html = "";
		$dropdownField = DropdownField::create($this->getName(), false, $this->getDropdownOptions(), $this->Value());
		$dropdownField->addExtraClass('presets');
		$dropdownField->setHasEmptyDefault(false);
		$dropdownField->setForm($this->getForm());
		$html .= $dropdownField->forTemplate();
		return $html;
	}

	public function Type() {
		return 'timedropdown time text';
	}

	public function getDropdownOptions(){
		$startOptions = array("" => "- Closed -");
		$endOptions = array("" => "- Closed -");
		for($i=0; $i < 24; $i++) {
			$t = str_pad($i, 2, "0", STR_PAD_LEFT);
			if($i > 3 && $i < 12) {
				$startOptions[date("g:i:s A", strtotime($t.":00:00"))] = date("g:i A", strtotime($t.":00:00"));
				$startOptions[date("g:i:s A", strtotime($t.":30:00"))] = date("g:i A", strtotime($t.":30:00"));
			}
			if($i >= 11 && $i < 24) {
				$endOptions[date("g:i:s A", strtotime($t.":00:00"))] = date("g:i A", strtotime($t.":00:00"));
				$endOptions[date("g:i:s A", strtotime($t.":30:00"))] = date("g:i A", strtotime($t.":30:00"));
			}
		}
		if($this->morningOnly || !$this->afternoonOnly) {
			return $startOptions;
		}
		if($this->afternoonOnly) {
			return $endOptions;
		}
		return $startOptions + $endOptions;
	}

	function setMorningOnly($b) {
		$this->morningOnly = true;
	}

	function setAfternoonOnly($b) {
		$this->afternoonOnly = true;
	}

}
